### ISSUE TITLE
can't manage images if not on hub.docker.com

### ISSUE THREAD

**Issue by SydOps** [CenturyLinkLabs/imagelayers#24]
I'd like to check the size of  `b.gcr.io/tensorflow/tensorflow`, I can't

**Comment by davidgardner11** [comment]
Hi @SydOps, as a publicly hosted tool, imagelayers.io does not have a mechanism for securely storing private registry credentials. However, you are welcome to fork and modify the project to do so. 
You could even just hardcode the credentials for the registry you want to connect to and use it locally.

**Comment by SydOps** [comment]
Thanks, @davidgardner11 

could you please point me the right direction that which files I need target to add this feature, if I want to help?

**Comment by whiteadam** [comment]
+1

**Comment by ismarslomic** [comment]
@davidgardner11  Could you please give us some hint which files we need to modify in order to run this container locally and connect to private registry?

**Comment by m3talstorm** [comment]
@ismarslomic 

> imagelayers\Godeps\_workspace\src\github.com\CenturyLinkLabs\docker-reg-client\registry\registry.go


Has:

```
const (
	defaultBaseURL = "https://index.docker.io/v1/"
)
```
